name: NPM Publish

on:
    push:
        branches: ['master']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.2

            - name: Setup pnpm
              uses: pnpm/action-setup@v3.0.0
              with:
                  version: 8.15.5

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v4.0.2
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Setup NodeJS
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Set publishing config
              shell: bash
              run: |
                  pnpm config set "registry" "https://registry.npmjs.org/"
                  pnpm config set "//registry.npmjs.org/:_authToken" "$NODE_AUTH_TOKEN"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm run test

            - name: Build packge
              run: pnpm run build

            - name: Publish package
              run: pnpm publish --access=public --no-git-checks
